# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello_world.proto for package ''

require "grpc"
require_relative "hello_world_pb"

module Greeter
  # The greeting service definition.
  class Service
    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = "Greeter"

    # Sends a greeting
    rpc :SayHello, ::HelloRequest, ::HelloReply
    # Sends another greeting
    rpc :SayHelloAgain, ::HelloRequest, ::HelloReply
  end

  Stub = Service.rpc_stub_class
end
